// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: buildSheet.proto

#ifndef PROTOBUF_buildSheet_2eproto__INCLUDED
#define PROTOBUF_buildSheet_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace WakfuProto {
class ProtoBuildSheet;
class ProtoBuildSheetDefaultTypeInternal;
extern ProtoBuildSheetDefaultTypeInternal _ProtoBuildSheet_default_instance_;
class ProtoBuildSheetSet;
class ProtoBuildSheetSetDefaultTypeInternal;
extern ProtoBuildSheetSetDefaultTypeInternal _ProtoBuildSheetSet_default_instance_;
}  // namespace WakfuProto

namespace WakfuProto {

namespace protobuf_buildSheet_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_buildSheet_2eproto

// ===================================================================

class ProtoBuildSheetSet : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:WakfuProto.ProtoBuildSheetSet) */ {
 public:
  ProtoBuildSheetSet();
  virtual ~ProtoBuildSheetSet();

  ProtoBuildSheetSet(const ProtoBuildSheetSet& from);

  inline ProtoBuildSheetSet& operator=(const ProtoBuildSheetSet& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ProtoBuildSheetSet& default_instance();

  static inline const ProtoBuildSheetSet* internal_default_instance() {
    return reinterpret_cast<const ProtoBuildSheetSet*>(
               &_ProtoBuildSheetSet_default_instance_);
  }

  void Swap(ProtoBuildSheetSet* other);

  // implements Message ----------------------------------------------

  inline ProtoBuildSheetSet* New() const PROTOBUF_FINAL { return New(NULL); }

  ProtoBuildSheetSet* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ProtoBuildSheetSet& from);
  void MergeFrom(const ProtoBuildSheetSet& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ProtoBuildSheetSet* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .WakfuProto.ProtoBuildSheet buildSheets = 2;
  int buildsheets_size() const;
  void clear_buildsheets();
  static const int kBuildSheetsFieldNumber = 2;
  const ::WakfuProto::ProtoBuildSheet& buildsheets(int index) const;
  ::WakfuProto::ProtoBuildSheet* mutable_buildsheets(int index);
  ::WakfuProto::ProtoBuildSheet* add_buildsheets();
  ::google::protobuf::RepeatedPtrField< ::WakfuProto::ProtoBuildSheet >*
      mutable_buildsheets();
  const ::google::protobuf::RepeatedPtrField< ::WakfuProto::ProtoBuildSheet >&
      buildsheets() const;

  // required .WakfuProto.ProtoBuildSheet automaticSheet = 3;
  bool has_automaticsheet() const;
  void clear_automaticsheet();
  static const int kAutomaticSheetFieldNumber = 3;
  const ::WakfuProto::ProtoBuildSheet& automaticsheet() const;
  ::WakfuProto::ProtoBuildSheet* mutable_automaticsheet();
  ::WakfuProto::ProtoBuildSheet* release_automaticsheet();
  void set_allocated_automaticsheet(::WakfuProto::ProtoBuildSheet* automaticsheet);

  // required int32 activeSheetIndex = 1;
  bool has_activesheetindex() const;
  void clear_activesheetindex();
  static const int kActiveSheetIndexFieldNumber = 1;
  ::google::protobuf::int32 activesheetindex() const;
  void set_activesheetindex(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:WakfuProto.ProtoBuildSheetSet)
 private:
  void set_has_activesheetindex();
  void clear_has_activesheetindex();
  void set_has_automaticsheet();
  void clear_has_automaticsheet();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::WakfuProto::ProtoBuildSheet > buildsheets_;
  ::WakfuProto::ProtoBuildSheet* automaticsheet_;
  ::google::protobuf::int32 activesheetindex_;
  friend struct  protobuf_buildSheet_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ProtoBuildSheet : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:WakfuProto.ProtoBuildSheet) */ {
 public:
  ProtoBuildSheet();
  virtual ~ProtoBuildSheet();

  ProtoBuildSheet(const ProtoBuildSheet& from);

  inline ProtoBuildSheet& operator=(const ProtoBuildSheet& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ProtoBuildSheet& default_instance();

  static inline const ProtoBuildSheet* internal_default_instance() {
    return reinterpret_cast<const ProtoBuildSheet*>(
               &_ProtoBuildSheet_default_instance_);
  }

  void Swap(ProtoBuildSheet* other);

  // implements Message ----------------------------------------------

  inline ProtoBuildSheet* New() const PROTOBUF_FINAL { return New(NULL); }

  ProtoBuildSheet* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ProtoBuildSheet& from);
  void MergeFrom(const ProtoBuildSheet& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ProtoBuildSheet* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string name = 2;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 2;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // required int32 index = 1;
  bool has_index() const;
  void clear_index();
  static const int kIndexFieldNumber = 1;
  ::google::protobuf::int32 index() const;
  void set_index(::google::protobuf::int32 value);

  // required int32 level = 3;
  bool has_level() const;
  void clear_level();
  static const int kLevelFieldNumber = 3;
  ::google::protobuf::int32 level() const;
  void set_level(::google::protobuf::int32 value);

  // required int32 spellDeckIndex = 4;
  bool has_spelldeckindex() const;
  void clear_spelldeckindex();
  static const int kSpellDeckIndexFieldNumber = 4;
  ::google::protobuf::int32 spelldeckindex() const;
  void set_spelldeckindex(::google::protobuf::int32 value);

  // required int32 aptitudeSheetIndex = 5;
  bool has_aptitudesheetindex() const;
  void clear_aptitudesheetindex();
  static const int kAptitudeSheetIndexFieldNumber = 5;
  ::google::protobuf::int32 aptitudesheetindex() const;
  void set_aptitudesheetindex(::google::protobuf::int32 value);

  // required int32 equipmentSheetIndex = 6;
  bool has_equipmentsheetindex() const;
  void clear_equipmentsheetindex();
  static const int kEquipmentSheetIndexFieldNumber = 6;
  ::google::protobuf::int32 equipmentsheetindex() const;
  void set_equipmentsheetindex(::google::protobuf::int32 value);

  // required int32 iconIndex = 7;
  bool has_iconindex() const;
  void clear_iconindex();
  static const int kIconIndexFieldNumber = 7;
  ::google::protobuf::int32 iconindex() const;
  void set_iconindex(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:WakfuProto.ProtoBuildSheet)
 private:
  void set_has_index();
  void clear_has_index();
  void set_has_name();
  void clear_has_name();
  void set_has_level();
  void clear_has_level();
  void set_has_spelldeckindex();
  void clear_has_spelldeckindex();
  void set_has_aptitudesheetindex();
  void clear_has_aptitudesheetindex();
  void set_has_equipmentsheetindex();
  void clear_has_equipmentsheetindex();
  void set_has_iconindex();
  void clear_has_iconindex();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::int32 index_;
  ::google::protobuf::int32 level_;
  ::google::protobuf::int32 spelldeckindex_;
  ::google::protobuf::int32 aptitudesheetindex_;
  ::google::protobuf::int32 equipmentsheetindex_;
  ::google::protobuf::int32 iconindex_;
  friend struct  protobuf_buildSheet_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// ProtoBuildSheetSet

// required int32 activeSheetIndex = 1;
inline bool ProtoBuildSheetSet::has_activesheetindex() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ProtoBuildSheetSet::set_has_activesheetindex() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ProtoBuildSheetSet::clear_has_activesheetindex() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ProtoBuildSheetSet::clear_activesheetindex() {
  activesheetindex_ = 0;
  clear_has_activesheetindex();
}
inline ::google::protobuf::int32 ProtoBuildSheetSet::activesheetindex() const {
  // @@protoc_insertion_point(field_get:WakfuProto.ProtoBuildSheetSet.activeSheetIndex)
  return activesheetindex_;
}
inline void ProtoBuildSheetSet::set_activesheetindex(::google::protobuf::int32 value) {
  set_has_activesheetindex();
  activesheetindex_ = value;
  // @@protoc_insertion_point(field_set:WakfuProto.ProtoBuildSheetSet.activeSheetIndex)
}

// repeated .WakfuProto.ProtoBuildSheet buildSheets = 2;
inline int ProtoBuildSheetSet::buildsheets_size() const {
  return buildsheets_.size();
}
inline void ProtoBuildSheetSet::clear_buildsheets() {
  buildsheets_.Clear();
}
inline const ::WakfuProto::ProtoBuildSheet& ProtoBuildSheetSet::buildsheets(int index) const {
  // @@protoc_insertion_point(field_get:WakfuProto.ProtoBuildSheetSet.buildSheets)
  return buildsheets_.Get(index);
}
inline ::WakfuProto::ProtoBuildSheet* ProtoBuildSheetSet::mutable_buildsheets(int index) {
  // @@protoc_insertion_point(field_mutable:WakfuProto.ProtoBuildSheetSet.buildSheets)
  return buildsheets_.Mutable(index);
}
inline ::WakfuProto::ProtoBuildSheet* ProtoBuildSheetSet::add_buildsheets() {
  // @@protoc_insertion_point(field_add:WakfuProto.ProtoBuildSheetSet.buildSheets)
  return buildsheets_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::WakfuProto::ProtoBuildSheet >*
ProtoBuildSheetSet::mutable_buildsheets() {
  // @@protoc_insertion_point(field_mutable_list:WakfuProto.ProtoBuildSheetSet.buildSheets)
  return &buildsheets_;
}
inline const ::google::protobuf::RepeatedPtrField< ::WakfuProto::ProtoBuildSheet >&
ProtoBuildSheetSet::buildsheets() const {
  // @@protoc_insertion_point(field_list:WakfuProto.ProtoBuildSheetSet.buildSheets)
  return buildsheets_;
}

// required .WakfuProto.ProtoBuildSheet automaticSheet = 3;
inline bool ProtoBuildSheetSet::has_automaticsheet() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ProtoBuildSheetSet::set_has_automaticsheet() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ProtoBuildSheetSet::clear_has_automaticsheet() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ProtoBuildSheetSet::clear_automaticsheet() {
  if (automaticsheet_ != NULL) automaticsheet_->::WakfuProto::ProtoBuildSheet::Clear();
  clear_has_automaticsheet();
}
inline const ::WakfuProto::ProtoBuildSheet& ProtoBuildSheetSet::automaticsheet() const {
  // @@protoc_insertion_point(field_get:WakfuProto.ProtoBuildSheetSet.automaticSheet)
  return automaticsheet_ != NULL ? *automaticsheet_
                         : *::WakfuProto::ProtoBuildSheet::internal_default_instance();
}
inline ::WakfuProto::ProtoBuildSheet* ProtoBuildSheetSet::mutable_automaticsheet() {
  set_has_automaticsheet();
  if (automaticsheet_ == NULL) {
    automaticsheet_ = new ::WakfuProto::ProtoBuildSheet;
  }
  // @@protoc_insertion_point(field_mutable:WakfuProto.ProtoBuildSheetSet.automaticSheet)
  return automaticsheet_;
}
inline ::WakfuProto::ProtoBuildSheet* ProtoBuildSheetSet::release_automaticsheet() {
  // @@protoc_insertion_point(field_release:WakfuProto.ProtoBuildSheetSet.automaticSheet)
  clear_has_automaticsheet();
  ::WakfuProto::ProtoBuildSheet* temp = automaticsheet_;
  automaticsheet_ = NULL;
  return temp;
}
inline void ProtoBuildSheetSet::set_allocated_automaticsheet(::WakfuProto::ProtoBuildSheet* automaticsheet) {
  delete automaticsheet_;
  automaticsheet_ = automaticsheet;
  if (automaticsheet) {
    set_has_automaticsheet();
  } else {
    clear_has_automaticsheet();
  }
  // @@protoc_insertion_point(field_set_allocated:WakfuProto.ProtoBuildSheetSet.automaticSheet)
}

// -------------------------------------------------------------------

// ProtoBuildSheet

// required int32 index = 1;
inline bool ProtoBuildSheet::has_index() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ProtoBuildSheet::set_has_index() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ProtoBuildSheet::clear_has_index() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ProtoBuildSheet::clear_index() {
  index_ = 0;
  clear_has_index();
}
inline ::google::protobuf::int32 ProtoBuildSheet::index() const {
  // @@protoc_insertion_point(field_get:WakfuProto.ProtoBuildSheet.index)
  return index_;
}
inline void ProtoBuildSheet::set_index(::google::protobuf::int32 value) {
  set_has_index();
  index_ = value;
  // @@protoc_insertion_point(field_set:WakfuProto.ProtoBuildSheet.index)
}

// required string name = 2;
inline bool ProtoBuildSheet::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ProtoBuildSheet::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ProtoBuildSheet::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ProtoBuildSheet::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& ProtoBuildSheet::name() const {
  // @@protoc_insertion_point(field_get:WakfuProto.ProtoBuildSheet.name)
  return name_.GetNoArena();
}
inline void ProtoBuildSheet::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:WakfuProto.ProtoBuildSheet.name)
}
#if LANG_CXX11
inline void ProtoBuildSheet::set_name(::std::string&& value) {
  set_has_name();
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:WakfuProto.ProtoBuildSheet.name)
}
#endif
inline void ProtoBuildSheet::set_name(const char* value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:WakfuProto.ProtoBuildSheet.name)
}
inline void ProtoBuildSheet::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:WakfuProto.ProtoBuildSheet.name)
}
inline ::std::string* ProtoBuildSheet::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:WakfuProto.ProtoBuildSheet.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ProtoBuildSheet::release_name() {
  // @@protoc_insertion_point(field_release:WakfuProto.ProtoBuildSheet.name)
  clear_has_name();
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ProtoBuildSheet::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:WakfuProto.ProtoBuildSheet.name)
}

// required int32 level = 3;
inline bool ProtoBuildSheet::has_level() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ProtoBuildSheet::set_has_level() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ProtoBuildSheet::clear_has_level() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ProtoBuildSheet::clear_level() {
  level_ = 0;
  clear_has_level();
}
inline ::google::protobuf::int32 ProtoBuildSheet::level() const {
  // @@protoc_insertion_point(field_get:WakfuProto.ProtoBuildSheet.level)
  return level_;
}
inline void ProtoBuildSheet::set_level(::google::protobuf::int32 value) {
  set_has_level();
  level_ = value;
  // @@protoc_insertion_point(field_set:WakfuProto.ProtoBuildSheet.level)
}

// required int32 spellDeckIndex = 4;
inline bool ProtoBuildSheet::has_spelldeckindex() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ProtoBuildSheet::set_has_spelldeckindex() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ProtoBuildSheet::clear_has_spelldeckindex() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ProtoBuildSheet::clear_spelldeckindex() {
  spelldeckindex_ = 0;
  clear_has_spelldeckindex();
}
inline ::google::protobuf::int32 ProtoBuildSheet::spelldeckindex() const {
  // @@protoc_insertion_point(field_get:WakfuProto.ProtoBuildSheet.spellDeckIndex)
  return spelldeckindex_;
}
inline void ProtoBuildSheet::set_spelldeckindex(::google::protobuf::int32 value) {
  set_has_spelldeckindex();
  spelldeckindex_ = value;
  // @@protoc_insertion_point(field_set:WakfuProto.ProtoBuildSheet.spellDeckIndex)
}

// required int32 aptitudeSheetIndex = 5;
inline bool ProtoBuildSheet::has_aptitudesheetindex() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void ProtoBuildSheet::set_has_aptitudesheetindex() {
  _has_bits_[0] |= 0x00000010u;
}
inline void ProtoBuildSheet::clear_has_aptitudesheetindex() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void ProtoBuildSheet::clear_aptitudesheetindex() {
  aptitudesheetindex_ = 0;
  clear_has_aptitudesheetindex();
}
inline ::google::protobuf::int32 ProtoBuildSheet::aptitudesheetindex() const {
  // @@protoc_insertion_point(field_get:WakfuProto.ProtoBuildSheet.aptitudeSheetIndex)
  return aptitudesheetindex_;
}
inline void ProtoBuildSheet::set_aptitudesheetindex(::google::protobuf::int32 value) {
  set_has_aptitudesheetindex();
  aptitudesheetindex_ = value;
  // @@protoc_insertion_point(field_set:WakfuProto.ProtoBuildSheet.aptitudeSheetIndex)
}

// required int32 equipmentSheetIndex = 6;
inline bool ProtoBuildSheet::has_equipmentsheetindex() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void ProtoBuildSheet::set_has_equipmentsheetindex() {
  _has_bits_[0] |= 0x00000020u;
}
inline void ProtoBuildSheet::clear_has_equipmentsheetindex() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void ProtoBuildSheet::clear_equipmentsheetindex() {
  equipmentsheetindex_ = 0;
  clear_has_equipmentsheetindex();
}
inline ::google::protobuf::int32 ProtoBuildSheet::equipmentsheetindex() const {
  // @@protoc_insertion_point(field_get:WakfuProto.ProtoBuildSheet.equipmentSheetIndex)
  return equipmentsheetindex_;
}
inline void ProtoBuildSheet::set_equipmentsheetindex(::google::protobuf::int32 value) {
  set_has_equipmentsheetindex();
  equipmentsheetindex_ = value;
  // @@protoc_insertion_point(field_set:WakfuProto.ProtoBuildSheet.equipmentSheetIndex)
}

// required int32 iconIndex = 7;
inline bool ProtoBuildSheet::has_iconindex() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void ProtoBuildSheet::set_has_iconindex() {
  _has_bits_[0] |= 0x00000040u;
}
inline void ProtoBuildSheet::clear_has_iconindex() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void ProtoBuildSheet::clear_iconindex() {
  iconindex_ = 0;
  clear_has_iconindex();
}
inline ::google::protobuf::int32 ProtoBuildSheet::iconindex() const {
  // @@protoc_insertion_point(field_get:WakfuProto.ProtoBuildSheet.iconIndex)
  return iconindex_;
}
inline void ProtoBuildSheet::set_iconindex(::google::protobuf::int32 value) {
  set_has_iconindex();
  iconindex_ = value;
  // @@protoc_insertion_point(field_set:WakfuProto.ProtoBuildSheet.iconIndex)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace WakfuProto

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_buildSheet_2eproto__INCLUDED
