// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dimensionalBag.proto

#ifndef PROTOBUF_dimensionalBag_2eproto__INCLUDED
#define PROTOBUF_dimensionalBag_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace WakfuProto {
class ProtoDimensionalBagCategoryFee;
class ProtoDimensionalBagCategoryFeeDefaultTypeInternal;
extern ProtoDimensionalBagCategoryFeeDefaultTypeInternal _ProtoDimensionalBagCategoryFee_default_instance_;
class ProtoDimensionalBagCraftFee;
class ProtoDimensionalBagCraftFeeDefaultTypeInternal;
extern ProtoDimensionalBagCraftFeeDefaultTypeInternal _ProtoDimensionalBagCraftFee_default_instance_;
}  // namespace WakfuProto

namespace WakfuProto {

namespace protobuf_dimensionalBag_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_dimensionalBag_2eproto

// ===================================================================

class ProtoDimensionalBagCraftFee : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:WakfuProto.ProtoDimensionalBagCraftFee) */ {
 public:
  ProtoDimensionalBagCraftFee();
  virtual ~ProtoDimensionalBagCraftFee();

  ProtoDimensionalBagCraftFee(const ProtoDimensionalBagCraftFee& from);

  inline ProtoDimensionalBagCraftFee& operator=(const ProtoDimensionalBagCraftFee& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ProtoDimensionalBagCraftFee& default_instance();

  static inline const ProtoDimensionalBagCraftFee* internal_default_instance() {
    return reinterpret_cast<const ProtoDimensionalBagCraftFee*>(
               &_ProtoDimensionalBagCraftFee_default_instance_);
  }

  void Swap(ProtoDimensionalBagCraftFee* other);

  // implements Message ----------------------------------------------

  inline ProtoDimensionalBagCraftFee* New() const PROTOBUF_FINAL { return New(NULL); }

  ProtoDimensionalBagCraftFee* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ProtoDimensionalBagCraftFee& from);
  void MergeFrom(const ProtoDimensionalBagCraftFee& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ProtoDimensionalBagCraftFee* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .WakfuProto.ProtoDimensionalBagCategoryFee categoryFee = 1;
  int categoryfee_size() const;
  void clear_categoryfee();
  static const int kCategoryFeeFieldNumber = 1;
  const ::WakfuProto::ProtoDimensionalBagCategoryFee& categoryfee(int index) const;
  ::WakfuProto::ProtoDimensionalBagCategoryFee* mutable_categoryfee(int index);
  ::WakfuProto::ProtoDimensionalBagCategoryFee* add_categoryfee();
  ::google::protobuf::RepeatedPtrField< ::WakfuProto::ProtoDimensionalBagCategoryFee >*
      mutable_categoryfee();
  const ::google::protobuf::RepeatedPtrField< ::WakfuProto::ProtoDimensionalBagCategoryFee >&
      categoryfee() const;

  // required bool isFreeForFriends = 2;
  bool has_isfreeforfriends() const;
  void clear_isfreeforfriends();
  static const int kIsFreeForFriendsFieldNumber = 2;
  bool isfreeforfriends() const;
  void set_isfreeforfriends(bool value);

  // required bool isFreeForGuild = 3;
  bool has_isfreeforguild() const;
  void clear_isfreeforguild();
  static const int kIsFreeForGuildFieldNumber = 3;
  bool isfreeforguild() const;
  void set_isfreeforguild(bool value);

  // @@protoc_insertion_point(class_scope:WakfuProto.ProtoDimensionalBagCraftFee)
 private:
  void set_has_isfreeforfriends();
  void clear_has_isfreeforfriends();
  void set_has_isfreeforguild();
  void clear_has_isfreeforguild();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::WakfuProto::ProtoDimensionalBagCategoryFee > categoryfee_;
  bool isfreeforfriends_;
  bool isfreeforguild_;
  friend struct  protobuf_dimensionalBag_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ProtoDimensionalBagCategoryFee : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:WakfuProto.ProtoDimensionalBagCategoryFee) */ {
 public:
  ProtoDimensionalBagCategoryFee();
  virtual ~ProtoDimensionalBagCategoryFee();

  ProtoDimensionalBagCategoryFee(const ProtoDimensionalBagCategoryFee& from);

  inline ProtoDimensionalBagCategoryFee& operator=(const ProtoDimensionalBagCategoryFee& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ProtoDimensionalBagCategoryFee& default_instance();

  static inline const ProtoDimensionalBagCategoryFee* internal_default_instance() {
    return reinterpret_cast<const ProtoDimensionalBagCategoryFee*>(
               &_ProtoDimensionalBagCategoryFee_default_instance_);
  }

  void Swap(ProtoDimensionalBagCategoryFee* other);

  // implements Message ----------------------------------------------

  inline ProtoDimensionalBagCategoryFee* New() const PROTOBUF_FINAL { return New(NULL); }

  ProtoDimensionalBagCategoryFee* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ProtoDimensionalBagCategoryFee& from);
  void MergeFrom(const ProtoDimensionalBagCategoryFee& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ProtoDimensionalBagCategoryFee* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 categoryIndex = 1;
  bool has_categoryindex() const;
  void clear_categoryindex();
  static const int kCategoryIndexFieldNumber = 1;
  ::google::protobuf::int32 categoryindex() const;
  void set_categoryindex(::google::protobuf::int32 value);

  // required int32 equipmentCraftFee = 2;
  bool has_equipmentcraftfee() const;
  void clear_equipmentcraftfee();
  static const int kEquipmentCraftFeeFieldNumber = 2;
  ::google::protobuf::int32 equipmentcraftfee() const;
  void set_equipmentcraftfee(::google::protobuf::int32 value);

  // required int32 componentCraftFee = 3;
  bool has_componentcraftfee() const;
  void clear_componentcraftfee();
  static const int kComponentCraftFeeFieldNumber = 3;
  ::google::protobuf::int32 componentcraftfee() const;
  void set_componentcraftfee(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:WakfuProto.ProtoDimensionalBagCategoryFee)
 private:
  void set_has_categoryindex();
  void clear_has_categoryindex();
  void set_has_equipmentcraftfee();
  void clear_has_equipmentcraftfee();
  void set_has_componentcraftfee();
  void clear_has_componentcraftfee();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int32 categoryindex_;
  ::google::protobuf::int32 equipmentcraftfee_;
  ::google::protobuf::int32 componentcraftfee_;
  friend struct  protobuf_dimensionalBag_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// ProtoDimensionalBagCraftFee

// repeated .WakfuProto.ProtoDimensionalBagCategoryFee categoryFee = 1;
inline int ProtoDimensionalBagCraftFee::categoryfee_size() const {
  return categoryfee_.size();
}
inline void ProtoDimensionalBagCraftFee::clear_categoryfee() {
  categoryfee_.Clear();
}
inline const ::WakfuProto::ProtoDimensionalBagCategoryFee& ProtoDimensionalBagCraftFee::categoryfee(int index) const {
  // @@protoc_insertion_point(field_get:WakfuProto.ProtoDimensionalBagCraftFee.categoryFee)
  return categoryfee_.Get(index);
}
inline ::WakfuProto::ProtoDimensionalBagCategoryFee* ProtoDimensionalBagCraftFee::mutable_categoryfee(int index) {
  // @@protoc_insertion_point(field_mutable:WakfuProto.ProtoDimensionalBagCraftFee.categoryFee)
  return categoryfee_.Mutable(index);
}
inline ::WakfuProto::ProtoDimensionalBagCategoryFee* ProtoDimensionalBagCraftFee::add_categoryfee() {
  // @@protoc_insertion_point(field_add:WakfuProto.ProtoDimensionalBagCraftFee.categoryFee)
  return categoryfee_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::WakfuProto::ProtoDimensionalBagCategoryFee >*
ProtoDimensionalBagCraftFee::mutable_categoryfee() {
  // @@protoc_insertion_point(field_mutable_list:WakfuProto.ProtoDimensionalBagCraftFee.categoryFee)
  return &categoryfee_;
}
inline const ::google::protobuf::RepeatedPtrField< ::WakfuProto::ProtoDimensionalBagCategoryFee >&
ProtoDimensionalBagCraftFee::categoryfee() const {
  // @@protoc_insertion_point(field_list:WakfuProto.ProtoDimensionalBagCraftFee.categoryFee)
  return categoryfee_;
}

// required bool isFreeForFriends = 2;
inline bool ProtoDimensionalBagCraftFee::has_isfreeforfriends() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ProtoDimensionalBagCraftFee::set_has_isfreeforfriends() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ProtoDimensionalBagCraftFee::clear_has_isfreeforfriends() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ProtoDimensionalBagCraftFee::clear_isfreeforfriends() {
  isfreeforfriends_ = false;
  clear_has_isfreeforfriends();
}
inline bool ProtoDimensionalBagCraftFee::isfreeforfriends() const {
  // @@protoc_insertion_point(field_get:WakfuProto.ProtoDimensionalBagCraftFee.isFreeForFriends)
  return isfreeforfriends_;
}
inline void ProtoDimensionalBagCraftFee::set_isfreeforfriends(bool value) {
  set_has_isfreeforfriends();
  isfreeforfriends_ = value;
  // @@protoc_insertion_point(field_set:WakfuProto.ProtoDimensionalBagCraftFee.isFreeForFriends)
}

// required bool isFreeForGuild = 3;
inline bool ProtoDimensionalBagCraftFee::has_isfreeforguild() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ProtoDimensionalBagCraftFee::set_has_isfreeforguild() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ProtoDimensionalBagCraftFee::clear_has_isfreeforguild() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ProtoDimensionalBagCraftFee::clear_isfreeforguild() {
  isfreeforguild_ = false;
  clear_has_isfreeforguild();
}
inline bool ProtoDimensionalBagCraftFee::isfreeforguild() const {
  // @@protoc_insertion_point(field_get:WakfuProto.ProtoDimensionalBagCraftFee.isFreeForGuild)
  return isfreeforguild_;
}
inline void ProtoDimensionalBagCraftFee::set_isfreeforguild(bool value) {
  set_has_isfreeforguild();
  isfreeforguild_ = value;
  // @@protoc_insertion_point(field_set:WakfuProto.ProtoDimensionalBagCraftFee.isFreeForGuild)
}

// -------------------------------------------------------------------

// ProtoDimensionalBagCategoryFee

// required int32 categoryIndex = 1;
inline bool ProtoDimensionalBagCategoryFee::has_categoryindex() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ProtoDimensionalBagCategoryFee::set_has_categoryindex() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ProtoDimensionalBagCategoryFee::clear_has_categoryindex() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ProtoDimensionalBagCategoryFee::clear_categoryindex() {
  categoryindex_ = 0;
  clear_has_categoryindex();
}
inline ::google::protobuf::int32 ProtoDimensionalBagCategoryFee::categoryindex() const {
  // @@protoc_insertion_point(field_get:WakfuProto.ProtoDimensionalBagCategoryFee.categoryIndex)
  return categoryindex_;
}
inline void ProtoDimensionalBagCategoryFee::set_categoryindex(::google::protobuf::int32 value) {
  set_has_categoryindex();
  categoryindex_ = value;
  // @@protoc_insertion_point(field_set:WakfuProto.ProtoDimensionalBagCategoryFee.categoryIndex)
}

// required int32 equipmentCraftFee = 2;
inline bool ProtoDimensionalBagCategoryFee::has_equipmentcraftfee() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ProtoDimensionalBagCategoryFee::set_has_equipmentcraftfee() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ProtoDimensionalBagCategoryFee::clear_has_equipmentcraftfee() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ProtoDimensionalBagCategoryFee::clear_equipmentcraftfee() {
  equipmentcraftfee_ = 0;
  clear_has_equipmentcraftfee();
}
inline ::google::protobuf::int32 ProtoDimensionalBagCategoryFee::equipmentcraftfee() const {
  // @@protoc_insertion_point(field_get:WakfuProto.ProtoDimensionalBagCategoryFee.equipmentCraftFee)
  return equipmentcraftfee_;
}
inline void ProtoDimensionalBagCategoryFee::set_equipmentcraftfee(::google::protobuf::int32 value) {
  set_has_equipmentcraftfee();
  equipmentcraftfee_ = value;
  // @@protoc_insertion_point(field_set:WakfuProto.ProtoDimensionalBagCategoryFee.equipmentCraftFee)
}

// required int32 componentCraftFee = 3;
inline bool ProtoDimensionalBagCategoryFee::has_componentcraftfee() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ProtoDimensionalBagCategoryFee::set_has_componentcraftfee() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ProtoDimensionalBagCategoryFee::clear_has_componentcraftfee() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ProtoDimensionalBagCategoryFee::clear_componentcraftfee() {
  componentcraftfee_ = 0;
  clear_has_componentcraftfee();
}
inline ::google::protobuf::int32 ProtoDimensionalBagCategoryFee::componentcraftfee() const {
  // @@protoc_insertion_point(field_get:WakfuProto.ProtoDimensionalBagCategoryFee.componentCraftFee)
  return componentcraftfee_;
}
inline void ProtoDimensionalBagCategoryFee::set_componentcraftfee(::google::protobuf::int32 value) {
  set_has_componentcraftfee();
  componentcraftfee_ = value;
  // @@protoc_insertion_point(field_set:WakfuProto.ProtoDimensionalBagCategoryFee.componentCraftFee)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace WakfuProto

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_dimensionalBag_2eproto__INCLUDED
