// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dungeon_progression.proto

#ifndef PROTOBUF_dungeon_5fprogression_2eproto__INCLUDED
#define PROTOBUF_dungeon_5fprogression_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace WakfuProto {
class ProtoDungeonEntry;
class ProtoDungeonEntryDefaultTypeInternal;
extern ProtoDungeonEntryDefaultTypeInternal _ProtoDungeonEntry_default_instance_;
class ProtoDungeonProgression;
class ProtoDungeonProgressionDefaultTypeInternal;
extern ProtoDungeonProgressionDefaultTypeInternal _ProtoDungeonProgression_default_instance_;
}  // namespace WakfuProto

namespace WakfuProto {

namespace protobuf_dungeon_5fprogression_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_dungeon_5fprogression_2eproto

// ===================================================================

class ProtoDungeonProgression : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:WakfuProto.ProtoDungeonProgression) */ {
 public:
  ProtoDungeonProgression();
  virtual ~ProtoDungeonProgression();

  ProtoDungeonProgression(const ProtoDungeonProgression& from);

  inline ProtoDungeonProgression& operator=(const ProtoDungeonProgression& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ProtoDungeonProgression& default_instance();

  static inline const ProtoDungeonProgression* internal_default_instance() {
    return reinterpret_cast<const ProtoDungeonProgression*>(
               &_ProtoDungeonProgression_default_instance_);
  }

  void Swap(ProtoDungeonProgression* other);

  // implements Message ----------------------------------------------

  inline ProtoDungeonProgression* New() const PROTOBUF_FINAL { return New(NULL); }

  ProtoDungeonProgression* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ProtoDungeonProgression& from);
  void MergeFrom(const ProtoDungeonProgression& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ProtoDungeonProgression* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .WakfuProto.ProtoDungeonEntry map = 1;
  int map_size() const;
  void clear_map();
  static const int kMapFieldNumber = 1;
  const ::WakfuProto::ProtoDungeonEntry& map(int index) const;
  ::WakfuProto::ProtoDungeonEntry* mutable_map(int index);
  ::WakfuProto::ProtoDungeonEntry* add_map();
  ::google::protobuf::RepeatedPtrField< ::WakfuProto::ProtoDungeonEntry >*
      mutable_map();
  const ::google::protobuf::RepeatedPtrField< ::WakfuProto::ProtoDungeonEntry >&
      map() const;

  // @@protoc_insertion_point(class_scope:WakfuProto.ProtoDungeonProgression)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::WakfuProto::ProtoDungeonEntry > map_;
  friend struct  protobuf_dungeon_5fprogression_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ProtoDungeonEntry : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:WakfuProto.ProtoDungeonEntry) */ {
 public:
  ProtoDungeonEntry();
  virtual ~ProtoDungeonEntry();

  ProtoDungeonEntry(const ProtoDungeonEntry& from);

  inline ProtoDungeonEntry& operator=(const ProtoDungeonEntry& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ProtoDungeonEntry& default_instance();

  static inline const ProtoDungeonEntry* internal_default_instance() {
    return reinterpret_cast<const ProtoDungeonEntry*>(
               &_ProtoDungeonEntry_default_instance_);
  }

  void Swap(ProtoDungeonEntry* other);

  // implements Message ----------------------------------------------

  inline ProtoDungeonEntry* New() const PROTOBUF_FINAL { return New(NULL); }

  ProtoDungeonEntry* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ProtoDungeonEntry& from);
  void MergeFrom(const ProtoDungeonEntry& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ProtoDungeonEntry* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 index = 1;
  bool has_index() const;
  void clear_index();
  static const int kIndexFieldNumber = 1;
  ::google::protobuf::int32 index() const;
  void set_index(::google::protobuf::int32 value);

  // required int32 difficulty = 2;
  bool has_difficulty() const;
  void clear_difficulty();
  static const int kDifficultyFieldNumber = 2;
  ::google::protobuf::int32 difficulty() const;
  void set_difficulty(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:WakfuProto.ProtoDungeonEntry)
 private:
  void set_has_index();
  void clear_has_index();
  void set_has_difficulty();
  void clear_has_difficulty();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int32 index_;
  ::google::protobuf::int32 difficulty_;
  friend struct  protobuf_dungeon_5fprogression_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// ProtoDungeonProgression

// repeated .WakfuProto.ProtoDungeonEntry map = 1;
inline int ProtoDungeonProgression::map_size() const {
  return map_.size();
}
inline void ProtoDungeonProgression::clear_map() {
  map_.Clear();
}
inline const ::WakfuProto::ProtoDungeonEntry& ProtoDungeonProgression::map(int index) const {
  // @@protoc_insertion_point(field_get:WakfuProto.ProtoDungeonProgression.map)
  return map_.Get(index);
}
inline ::WakfuProto::ProtoDungeonEntry* ProtoDungeonProgression::mutable_map(int index) {
  // @@protoc_insertion_point(field_mutable:WakfuProto.ProtoDungeonProgression.map)
  return map_.Mutable(index);
}
inline ::WakfuProto::ProtoDungeonEntry* ProtoDungeonProgression::add_map() {
  // @@protoc_insertion_point(field_add:WakfuProto.ProtoDungeonProgression.map)
  return map_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::WakfuProto::ProtoDungeonEntry >*
ProtoDungeonProgression::mutable_map() {
  // @@protoc_insertion_point(field_mutable_list:WakfuProto.ProtoDungeonProgression.map)
  return &map_;
}
inline const ::google::protobuf::RepeatedPtrField< ::WakfuProto::ProtoDungeonEntry >&
ProtoDungeonProgression::map() const {
  // @@protoc_insertion_point(field_list:WakfuProto.ProtoDungeonProgression.map)
  return map_;
}

// -------------------------------------------------------------------

// ProtoDungeonEntry

// required int32 index = 1;
inline bool ProtoDungeonEntry::has_index() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ProtoDungeonEntry::set_has_index() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ProtoDungeonEntry::clear_has_index() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ProtoDungeonEntry::clear_index() {
  index_ = 0;
  clear_has_index();
}
inline ::google::protobuf::int32 ProtoDungeonEntry::index() const {
  // @@protoc_insertion_point(field_get:WakfuProto.ProtoDungeonEntry.index)
  return index_;
}
inline void ProtoDungeonEntry::set_index(::google::protobuf::int32 value) {
  set_has_index();
  index_ = value;
  // @@protoc_insertion_point(field_set:WakfuProto.ProtoDungeonEntry.index)
}

// required int32 difficulty = 2;
inline bool ProtoDungeonEntry::has_difficulty() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ProtoDungeonEntry::set_has_difficulty() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ProtoDungeonEntry::clear_has_difficulty() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ProtoDungeonEntry::clear_difficulty() {
  difficulty_ = 0;
  clear_has_difficulty();
}
inline ::google::protobuf::int32 ProtoDungeonEntry::difficulty() const {
  // @@protoc_insertion_point(field_get:WakfuProto.ProtoDungeonEntry.difficulty)
  return difficulty_;
}
inline void ProtoDungeonEntry::set_difficulty(::google::protobuf::int32 value) {
  set_has_difficulty();
  difficulty_ = value;
  // @@protoc_insertion_point(field_set:WakfuProto.ProtoDungeonEntry.difficulty)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace WakfuProto

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_dungeon_5fprogression_2eproto__INCLUDED
