// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: equipment.proto

#ifndef PROTOBUF_equipment_2eproto__INCLUDED
#define PROTOBUF_equipment_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "item.pb.h"
// @@protoc_insertion_point(includes)
namespace WakfuProto {
class ProtoBag;
class ProtoBagDefaultTypeInternal;
extern ProtoBagDefaultTypeInternal _ProtoBag_default_instance_;
class ProtoBagItem;
class ProtoBagItemDefaultTypeInternal;
extern ProtoBagItemDefaultTypeInternal _ProtoBagItem_default_instance_;
class ProtoCharacterBags;
class ProtoCharacterBagsDefaultTypeInternal;
extern ProtoCharacterBagsDefaultTypeInternal _ProtoCharacterBags_default_instance_;
class ProtoCompanionInfo;
class ProtoCompanionInfoDefaultTypeInternal;
extern ProtoCompanionInfoDefaultTypeInternal _ProtoCompanionInfo_default_instance_;
class ProtoEquipmentAccount;
class ProtoEquipmentAccountDefaultTypeInternal;
extern ProtoEquipmentAccountDefaultTypeInternal _ProtoEquipmentAccount_default_instance_;
class ProtoEquipmentInventory;
class ProtoEquipmentInventoryDefaultTypeInternal;
extern ProtoEquipmentInventoryDefaultTypeInternal _ProtoEquipmentInventory_default_instance_;
class ProtoEquipmentSet;
class ProtoEquipmentSetDefaultTypeInternal;
extern ProtoEquipmentSetDefaultTypeInternal _ProtoEquipmentSet_default_instance_;
class ProtoEquipmentSheet;
class ProtoEquipmentSheetDefaultTypeInternal;
extern ProtoEquipmentSheetDefaultTypeInternal _ProtoEquipmentSheet_default_instance_;
class ProtoEquipmentSheet_ProtoEquipmentItem;
class ProtoEquipmentSheet_ProtoEquipmentItemDefaultTypeInternal;
extern ProtoEquipmentSheet_ProtoEquipmentItemDefaultTypeInternal _ProtoEquipmentSheet_ProtoEquipmentItem_default_instance_;
class ProtoGems;
class ProtoGemsDefaultTypeInternal;
extern ProtoGemsDefaultTypeInternal _ProtoGems_default_instance_;
class ProtoGems_ProtoGem;
class ProtoGems_ProtoGemDefaultTypeInternal;
extern ProtoGems_ProtoGemDefaultTypeInternal _ProtoGems_ProtoGem_default_instance_;
class ProtoItem;
class ProtoItemDefaultTypeInternal;
extern ProtoItemDefaultTypeInternal _ProtoItem_default_instance_;
class ProtoItemBind;
class ProtoItemBindDefaultTypeInternal;
extern ProtoItemBindDefaultTypeInternal _ProtoItemBind_default_instance_;
class ProtoItemElements;
class ProtoItemElementsDefaultTypeInternal;
extern ProtoItemElementsDefaultTypeInternal _ProtoItemElements_default_instance_;
class ProtoItemXp;
class ProtoItemXpDefaultTypeInternal;
extern ProtoItemXpDefaultTypeInternal _ProtoItemXp_default_instance_;
class ProtoMergedItems;
class ProtoMergedItemsDefaultTypeInternal;
extern ProtoMergedItemsDefaultTypeInternal _ProtoMergedItems_default_instance_;
class ProtoPet;
class ProtoPetDefaultTypeInternal;
extern ProtoPetDefaultTypeInternal _ProtoPet_default_instance_;
class ProtoRentInfo;
class ProtoRentInfoDefaultTypeInternal;
extern ProtoRentInfoDefaultTypeInternal _ProtoRentInfo_default_instance_;
class ProtoTemporaryInventory;
class ProtoTemporaryInventoryDefaultTypeInternal;
extern ProtoTemporaryInventoryDefaultTypeInternal _ProtoTemporaryInventory_default_instance_;
}  // namespace WakfuProto

namespace WakfuProto {

namespace protobuf_equipment_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_equipment_2eproto

// ===================================================================

class ProtoEquipmentSheet_ProtoEquipmentItem : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:WakfuProto.ProtoEquipmentSheet.ProtoEquipmentItem) */ {
 public:
  ProtoEquipmentSheet_ProtoEquipmentItem();
  virtual ~ProtoEquipmentSheet_ProtoEquipmentItem();

  ProtoEquipmentSheet_ProtoEquipmentItem(const ProtoEquipmentSheet_ProtoEquipmentItem& from);

  inline ProtoEquipmentSheet_ProtoEquipmentItem& operator=(const ProtoEquipmentSheet_ProtoEquipmentItem& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ProtoEquipmentSheet_ProtoEquipmentItem& default_instance();

  static inline const ProtoEquipmentSheet_ProtoEquipmentItem* internal_default_instance() {
    return reinterpret_cast<const ProtoEquipmentSheet_ProtoEquipmentItem*>(
               &_ProtoEquipmentSheet_ProtoEquipmentItem_default_instance_);
  }

  void Swap(ProtoEquipmentSheet_ProtoEquipmentItem* other);

  // implements Message ----------------------------------------------

  inline ProtoEquipmentSheet_ProtoEquipmentItem* New() const PROTOBUF_FINAL { return New(NULL); }

  ProtoEquipmentSheet_ProtoEquipmentItem* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ProtoEquipmentSheet_ProtoEquipmentItem& from);
  void MergeFrom(const ProtoEquipmentSheet_ProtoEquipmentItem& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ProtoEquipmentSheet_ProtoEquipmentItem* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 uid = 1;
  bool has_uid() const;
  void clear_uid();
  static const int kUidFieldNumber = 1;
  ::google::protobuf::int64 uid() const;
  void set_uid(::google::protobuf::int64 value);

  // required int32 position = 2;
  bool has_position() const;
  void clear_position();
  static const int kPositionFieldNumber = 2;
  ::google::protobuf::int32 position() const;
  void set_position(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:WakfuProto.ProtoEquipmentSheet.ProtoEquipmentItem)
 private:
  void set_has_uid();
  void clear_has_uid();
  void set_has_position();
  void clear_has_position();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int64 uid_;
  ::google::protobuf::int32 position_;
  friend struct  protobuf_equipment_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ProtoEquipmentSheet : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:WakfuProto.ProtoEquipmentSheet) */ {
 public:
  ProtoEquipmentSheet();
  virtual ~ProtoEquipmentSheet();

  ProtoEquipmentSheet(const ProtoEquipmentSheet& from);

  inline ProtoEquipmentSheet& operator=(const ProtoEquipmentSheet& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ProtoEquipmentSheet& default_instance();

  static inline const ProtoEquipmentSheet* internal_default_instance() {
    return reinterpret_cast<const ProtoEquipmentSheet*>(
               &_ProtoEquipmentSheet_default_instance_);
  }

  void Swap(ProtoEquipmentSheet* other);

  // implements Message ----------------------------------------------

  inline ProtoEquipmentSheet* New() const PROTOBUF_FINAL { return New(NULL); }

  ProtoEquipmentSheet* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ProtoEquipmentSheet& from);
  void MergeFrom(const ProtoEquipmentSheet& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ProtoEquipmentSheet* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef ProtoEquipmentSheet_ProtoEquipmentItem ProtoEquipmentItem;

  // accessors -------------------------------------------------------

  // repeated .WakfuProto.ProtoEquipmentSheet.ProtoEquipmentItem items = 1;
  int items_size() const;
  void clear_items();
  static const int kItemsFieldNumber = 1;
  const ::WakfuProto::ProtoEquipmentSheet_ProtoEquipmentItem& items(int index) const;
  ::WakfuProto::ProtoEquipmentSheet_ProtoEquipmentItem* mutable_items(int index);
  ::WakfuProto::ProtoEquipmentSheet_ProtoEquipmentItem* add_items();
  ::google::protobuf::RepeatedPtrField< ::WakfuProto::ProtoEquipmentSheet_ProtoEquipmentItem >*
      mutable_items();
  const ::google::protobuf::RepeatedPtrField< ::WakfuProto::ProtoEquipmentSheet_ProtoEquipmentItem >&
      items() const;

  // optional string name = 52;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 52;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional int32 index = 51;
  bool has_index() const;
  void clear_index();
  static const int kIndexFieldNumber = 51;
  ::google::protobuf::int32 index() const;
  void set_index(::google::protobuf::int32 value);

  // optional int32 level = 53;
  bool has_level() const;
  void clear_level();
  static const int kLevelFieldNumber = 53;
  ::google::protobuf::int32 level() const;
  void set_level(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:WakfuProto.ProtoEquipmentSheet)
 private:
  void set_has_index();
  void clear_has_index();
  void set_has_name();
  void clear_has_name();
  void set_has_level();
  void clear_has_level();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::WakfuProto::ProtoEquipmentSheet_ProtoEquipmentItem > items_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::int32 index_;
  ::google::protobuf::int32 level_;
  friend struct  protobuf_equipment_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ProtoEquipmentSet : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:WakfuProto.ProtoEquipmentSet) */ {
 public:
  ProtoEquipmentSet();
  virtual ~ProtoEquipmentSet();

  ProtoEquipmentSet(const ProtoEquipmentSet& from);

  inline ProtoEquipmentSet& operator=(const ProtoEquipmentSet& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ProtoEquipmentSet& default_instance();

  static inline const ProtoEquipmentSet* internal_default_instance() {
    return reinterpret_cast<const ProtoEquipmentSet*>(
               &_ProtoEquipmentSet_default_instance_);
  }

  void Swap(ProtoEquipmentSet* other);

  // implements Message ----------------------------------------------

  inline ProtoEquipmentSet* New() const PROTOBUF_FINAL { return New(NULL); }

  ProtoEquipmentSet* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ProtoEquipmentSet& from);
  void MergeFrom(const ProtoEquipmentSet& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ProtoEquipmentSet* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .WakfuProto.ProtoEquipmentSheet sheets = 1;
  int sheets_size() const;
  void clear_sheets();
  static const int kSheetsFieldNumber = 1;
  const ::WakfuProto::ProtoEquipmentSheet& sheets(int index) const;
  ::WakfuProto::ProtoEquipmentSheet* mutable_sheets(int index);
  ::WakfuProto::ProtoEquipmentSheet* add_sheets();
  ::google::protobuf::RepeatedPtrField< ::WakfuProto::ProtoEquipmentSheet >*
      mutable_sheets();
  const ::google::protobuf::RepeatedPtrField< ::WakfuProto::ProtoEquipmentSheet >&
      sheets() const;

  // optional int64 characterId = 2;
  bool has_characterid() const;
  void clear_characterid();
  static const int kCharacterIdFieldNumber = 2;
  ::google::protobuf::int64 characterid() const;
  void set_characterid(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:WakfuProto.ProtoEquipmentSet)
 private:
  void set_has_characterid();
  void clear_has_characterid();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::WakfuProto::ProtoEquipmentSheet > sheets_;
  ::google::protobuf::int64 characterid_;
  friend struct  protobuf_equipment_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ProtoEquipmentAccount : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:WakfuProto.ProtoEquipmentAccount) */ {
 public:
  ProtoEquipmentAccount();
  virtual ~ProtoEquipmentAccount();

  ProtoEquipmentAccount(const ProtoEquipmentAccount& from);

  inline ProtoEquipmentAccount& operator=(const ProtoEquipmentAccount& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ProtoEquipmentAccount& default_instance();

  static inline const ProtoEquipmentAccount* internal_default_instance() {
    return reinterpret_cast<const ProtoEquipmentAccount*>(
               &_ProtoEquipmentAccount_default_instance_);
  }

  void Swap(ProtoEquipmentAccount* other);

  // implements Message ----------------------------------------------

  inline ProtoEquipmentAccount* New() const PROTOBUF_FINAL { return New(NULL); }

  ProtoEquipmentAccount* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ProtoEquipmentAccount& from);
  void MergeFrom(const ProtoEquipmentAccount& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ProtoEquipmentAccount* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .WakfuProto.ProtoEquipmentSet sets = 1;
  int sets_size() const;
  void clear_sets();
  static const int kSetsFieldNumber = 1;
  const ::WakfuProto::ProtoEquipmentSet& sets(int index) const;
  ::WakfuProto::ProtoEquipmentSet* mutable_sets(int index);
  ::WakfuProto::ProtoEquipmentSet* add_sets();
  ::google::protobuf::RepeatedPtrField< ::WakfuProto::ProtoEquipmentSet >*
      mutable_sets();
  const ::google::protobuf::RepeatedPtrField< ::WakfuProto::ProtoEquipmentSet >&
      sets() const;

  // @@protoc_insertion_point(class_scope:WakfuProto.ProtoEquipmentAccount)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::WakfuProto::ProtoEquipmentSet > sets_;
  friend struct  protobuf_equipment_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ProtoEquipmentInventory : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:WakfuProto.ProtoEquipmentInventory) */ {
 public:
  ProtoEquipmentInventory();
  virtual ~ProtoEquipmentInventory();

  ProtoEquipmentInventory(const ProtoEquipmentInventory& from);

  inline ProtoEquipmentInventory& operator=(const ProtoEquipmentInventory& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ProtoEquipmentInventory& default_instance();

  static inline const ProtoEquipmentInventory* internal_default_instance() {
    return reinterpret_cast<const ProtoEquipmentInventory*>(
               &_ProtoEquipmentInventory_default_instance_);
  }

  void Swap(ProtoEquipmentInventory* other);

  // implements Message ----------------------------------------------

  inline ProtoEquipmentInventory* New() const PROTOBUF_FINAL { return New(NULL); }

  ProtoEquipmentInventory* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ProtoEquipmentInventory& from);
  void MergeFrom(const ProtoEquipmentInventory& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ProtoEquipmentInventory* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .WakfuProto.ProtoItem items = 1;
  int items_size() const;
  void clear_items();
  static const int kItemsFieldNumber = 1;
  const ::WakfuProto::ProtoItem& items(int index) const;
  ::WakfuProto::ProtoItem* mutable_items(int index);
  ::WakfuProto::ProtoItem* add_items();
  ::google::protobuf::RepeatedPtrField< ::WakfuProto::ProtoItem >*
      mutable_items();
  const ::google::protobuf::RepeatedPtrField< ::WakfuProto::ProtoItem >&
      items() const;

  // @@protoc_insertion_point(class_scope:WakfuProto.ProtoEquipmentInventory)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::WakfuProto::ProtoItem > items_;
  friend struct  protobuf_equipment_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// ProtoEquipmentSheet_ProtoEquipmentItem

// required int64 uid = 1;
inline bool ProtoEquipmentSheet_ProtoEquipmentItem::has_uid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ProtoEquipmentSheet_ProtoEquipmentItem::set_has_uid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ProtoEquipmentSheet_ProtoEquipmentItem::clear_has_uid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ProtoEquipmentSheet_ProtoEquipmentItem::clear_uid() {
  uid_ = GOOGLE_LONGLONG(0);
  clear_has_uid();
}
inline ::google::protobuf::int64 ProtoEquipmentSheet_ProtoEquipmentItem::uid() const {
  // @@protoc_insertion_point(field_get:WakfuProto.ProtoEquipmentSheet.ProtoEquipmentItem.uid)
  return uid_;
}
inline void ProtoEquipmentSheet_ProtoEquipmentItem::set_uid(::google::protobuf::int64 value) {
  set_has_uid();
  uid_ = value;
  // @@protoc_insertion_point(field_set:WakfuProto.ProtoEquipmentSheet.ProtoEquipmentItem.uid)
}

// required int32 position = 2;
inline bool ProtoEquipmentSheet_ProtoEquipmentItem::has_position() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ProtoEquipmentSheet_ProtoEquipmentItem::set_has_position() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ProtoEquipmentSheet_ProtoEquipmentItem::clear_has_position() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ProtoEquipmentSheet_ProtoEquipmentItem::clear_position() {
  position_ = 0;
  clear_has_position();
}
inline ::google::protobuf::int32 ProtoEquipmentSheet_ProtoEquipmentItem::position() const {
  // @@protoc_insertion_point(field_get:WakfuProto.ProtoEquipmentSheet.ProtoEquipmentItem.position)
  return position_;
}
inline void ProtoEquipmentSheet_ProtoEquipmentItem::set_position(::google::protobuf::int32 value) {
  set_has_position();
  position_ = value;
  // @@protoc_insertion_point(field_set:WakfuProto.ProtoEquipmentSheet.ProtoEquipmentItem.position)
}

// -------------------------------------------------------------------

// ProtoEquipmentSheet

// repeated .WakfuProto.ProtoEquipmentSheet.ProtoEquipmentItem items = 1;
inline int ProtoEquipmentSheet::items_size() const {
  return items_.size();
}
inline void ProtoEquipmentSheet::clear_items() {
  items_.Clear();
}
inline const ::WakfuProto::ProtoEquipmentSheet_ProtoEquipmentItem& ProtoEquipmentSheet::items(int index) const {
  // @@protoc_insertion_point(field_get:WakfuProto.ProtoEquipmentSheet.items)
  return items_.Get(index);
}
inline ::WakfuProto::ProtoEquipmentSheet_ProtoEquipmentItem* ProtoEquipmentSheet::mutable_items(int index) {
  // @@protoc_insertion_point(field_mutable:WakfuProto.ProtoEquipmentSheet.items)
  return items_.Mutable(index);
}
inline ::WakfuProto::ProtoEquipmentSheet_ProtoEquipmentItem* ProtoEquipmentSheet::add_items() {
  // @@protoc_insertion_point(field_add:WakfuProto.ProtoEquipmentSheet.items)
  return items_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::WakfuProto::ProtoEquipmentSheet_ProtoEquipmentItem >*
ProtoEquipmentSheet::mutable_items() {
  // @@protoc_insertion_point(field_mutable_list:WakfuProto.ProtoEquipmentSheet.items)
  return &items_;
}
inline const ::google::protobuf::RepeatedPtrField< ::WakfuProto::ProtoEquipmentSheet_ProtoEquipmentItem >&
ProtoEquipmentSheet::items() const {
  // @@protoc_insertion_point(field_list:WakfuProto.ProtoEquipmentSheet.items)
  return items_;
}

// optional int32 index = 51;
inline bool ProtoEquipmentSheet::has_index() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ProtoEquipmentSheet::set_has_index() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ProtoEquipmentSheet::clear_has_index() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ProtoEquipmentSheet::clear_index() {
  index_ = 0;
  clear_has_index();
}
inline ::google::protobuf::int32 ProtoEquipmentSheet::index() const {
  // @@protoc_insertion_point(field_get:WakfuProto.ProtoEquipmentSheet.index)
  return index_;
}
inline void ProtoEquipmentSheet::set_index(::google::protobuf::int32 value) {
  set_has_index();
  index_ = value;
  // @@protoc_insertion_point(field_set:WakfuProto.ProtoEquipmentSheet.index)
}

// optional string name = 52;
inline bool ProtoEquipmentSheet::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ProtoEquipmentSheet::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ProtoEquipmentSheet::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ProtoEquipmentSheet::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& ProtoEquipmentSheet::name() const {
  // @@protoc_insertion_point(field_get:WakfuProto.ProtoEquipmentSheet.name)
  return name_.GetNoArena();
}
inline void ProtoEquipmentSheet::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:WakfuProto.ProtoEquipmentSheet.name)
}
#if LANG_CXX11
inline void ProtoEquipmentSheet::set_name(::std::string&& value) {
  set_has_name();
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:WakfuProto.ProtoEquipmentSheet.name)
}
#endif
inline void ProtoEquipmentSheet::set_name(const char* value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:WakfuProto.ProtoEquipmentSheet.name)
}
inline void ProtoEquipmentSheet::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:WakfuProto.ProtoEquipmentSheet.name)
}
inline ::std::string* ProtoEquipmentSheet::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:WakfuProto.ProtoEquipmentSheet.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ProtoEquipmentSheet::release_name() {
  // @@protoc_insertion_point(field_release:WakfuProto.ProtoEquipmentSheet.name)
  clear_has_name();
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ProtoEquipmentSheet::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:WakfuProto.ProtoEquipmentSheet.name)
}

// optional int32 level = 53;
inline bool ProtoEquipmentSheet::has_level() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ProtoEquipmentSheet::set_has_level() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ProtoEquipmentSheet::clear_has_level() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ProtoEquipmentSheet::clear_level() {
  level_ = 0;
  clear_has_level();
}
inline ::google::protobuf::int32 ProtoEquipmentSheet::level() const {
  // @@protoc_insertion_point(field_get:WakfuProto.ProtoEquipmentSheet.level)
  return level_;
}
inline void ProtoEquipmentSheet::set_level(::google::protobuf::int32 value) {
  set_has_level();
  level_ = value;
  // @@protoc_insertion_point(field_set:WakfuProto.ProtoEquipmentSheet.level)
}

// -------------------------------------------------------------------

// ProtoEquipmentSet

// repeated .WakfuProto.ProtoEquipmentSheet sheets = 1;
inline int ProtoEquipmentSet::sheets_size() const {
  return sheets_.size();
}
inline void ProtoEquipmentSet::clear_sheets() {
  sheets_.Clear();
}
inline const ::WakfuProto::ProtoEquipmentSheet& ProtoEquipmentSet::sheets(int index) const {
  // @@protoc_insertion_point(field_get:WakfuProto.ProtoEquipmentSet.sheets)
  return sheets_.Get(index);
}
inline ::WakfuProto::ProtoEquipmentSheet* ProtoEquipmentSet::mutable_sheets(int index) {
  // @@protoc_insertion_point(field_mutable:WakfuProto.ProtoEquipmentSet.sheets)
  return sheets_.Mutable(index);
}
inline ::WakfuProto::ProtoEquipmentSheet* ProtoEquipmentSet::add_sheets() {
  // @@protoc_insertion_point(field_add:WakfuProto.ProtoEquipmentSet.sheets)
  return sheets_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::WakfuProto::ProtoEquipmentSheet >*
ProtoEquipmentSet::mutable_sheets() {
  // @@protoc_insertion_point(field_mutable_list:WakfuProto.ProtoEquipmentSet.sheets)
  return &sheets_;
}
inline const ::google::protobuf::RepeatedPtrField< ::WakfuProto::ProtoEquipmentSheet >&
ProtoEquipmentSet::sheets() const {
  // @@protoc_insertion_point(field_list:WakfuProto.ProtoEquipmentSet.sheets)
  return sheets_;
}

// optional int64 characterId = 2;
inline bool ProtoEquipmentSet::has_characterid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ProtoEquipmentSet::set_has_characterid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ProtoEquipmentSet::clear_has_characterid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ProtoEquipmentSet::clear_characterid() {
  characterid_ = GOOGLE_LONGLONG(0);
  clear_has_characterid();
}
inline ::google::protobuf::int64 ProtoEquipmentSet::characterid() const {
  // @@protoc_insertion_point(field_get:WakfuProto.ProtoEquipmentSet.characterId)
  return characterid_;
}
inline void ProtoEquipmentSet::set_characterid(::google::protobuf::int64 value) {
  set_has_characterid();
  characterid_ = value;
  // @@protoc_insertion_point(field_set:WakfuProto.ProtoEquipmentSet.characterId)
}

// -------------------------------------------------------------------

// ProtoEquipmentAccount

// repeated .WakfuProto.ProtoEquipmentSet sets = 1;
inline int ProtoEquipmentAccount::sets_size() const {
  return sets_.size();
}
inline void ProtoEquipmentAccount::clear_sets() {
  sets_.Clear();
}
inline const ::WakfuProto::ProtoEquipmentSet& ProtoEquipmentAccount::sets(int index) const {
  // @@protoc_insertion_point(field_get:WakfuProto.ProtoEquipmentAccount.sets)
  return sets_.Get(index);
}
inline ::WakfuProto::ProtoEquipmentSet* ProtoEquipmentAccount::mutable_sets(int index) {
  // @@protoc_insertion_point(field_mutable:WakfuProto.ProtoEquipmentAccount.sets)
  return sets_.Mutable(index);
}
inline ::WakfuProto::ProtoEquipmentSet* ProtoEquipmentAccount::add_sets() {
  // @@protoc_insertion_point(field_add:WakfuProto.ProtoEquipmentAccount.sets)
  return sets_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::WakfuProto::ProtoEquipmentSet >*
ProtoEquipmentAccount::mutable_sets() {
  // @@protoc_insertion_point(field_mutable_list:WakfuProto.ProtoEquipmentAccount.sets)
  return &sets_;
}
inline const ::google::protobuf::RepeatedPtrField< ::WakfuProto::ProtoEquipmentSet >&
ProtoEquipmentAccount::sets() const {
  // @@protoc_insertion_point(field_list:WakfuProto.ProtoEquipmentAccount.sets)
  return sets_;
}

// -------------------------------------------------------------------

// ProtoEquipmentInventory

// repeated .WakfuProto.ProtoItem items = 1;
inline int ProtoEquipmentInventory::items_size() const {
  return items_.size();
}
inline void ProtoEquipmentInventory::clear_items() {
  items_.Clear();
}
inline const ::WakfuProto::ProtoItem& ProtoEquipmentInventory::items(int index) const {
  // @@protoc_insertion_point(field_get:WakfuProto.ProtoEquipmentInventory.items)
  return items_.Get(index);
}
inline ::WakfuProto::ProtoItem* ProtoEquipmentInventory::mutable_items(int index) {
  // @@protoc_insertion_point(field_mutable:WakfuProto.ProtoEquipmentInventory.items)
  return items_.Mutable(index);
}
inline ::WakfuProto::ProtoItem* ProtoEquipmentInventory::add_items() {
  // @@protoc_insertion_point(field_add:WakfuProto.ProtoEquipmentInventory.items)
  return items_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::WakfuProto::ProtoItem >*
ProtoEquipmentInventory::mutable_items() {
  // @@protoc_insertion_point(field_mutable_list:WakfuProto.ProtoEquipmentInventory.items)
  return &items_;
}
inline const ::google::protobuf::RepeatedPtrField< ::WakfuProto::ProtoItem >&
ProtoEquipmentInventory::items() const {
  // @@protoc_insertion_point(field_list:WakfuProto.ProtoEquipmentInventory.items)
  return items_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace WakfuProto

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_equipment_2eproto__INCLUDED
