CREATE DATABASE IF NOT EXISTS `wakbox_auth` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;

CREATE DATABASE IF NOT EXISTS `wakbox_char` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;

CREATE DATABASE IF NOT EXISTS `wakbox_world` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;